### PR TITLE
fix read file name

### PR DESCRIPTION
**Pull request by get-me-power**
I found a bug for read filename so I fixed. Please check this code.

### CODE REVIEW

**Comment by mattn** [comment]
The name of episode must be specified like below:

* `:StarWards sw1`
* Select episode via popup window

This behavior was changed in recent changes.

**Comment by get-me-power** [comment]
I see, but if I use `:StarWars` command for vim before support popup window, so I can only input number when select chapter. I input '1', but script don't move so I think this move is should fixed. What do you think?

## Reproduction
Untitled

**Comment by mattn** [comment]
Okay, I see. The patch must be

```diff
diff --git a/autoload/starwars.vim b/autoload/starwars.vim
index f1e8643..e40f085 100644
--- a/autoload/starwars.vim
+++ b/autoload/starwars.vim
@@ -10,6 +10,10 @@ function! starwars#play(...) abort
       return
     else
       let l:ep = inputlist(s:episodes)
+      if l:ep == 0
+        return
+      endif
+      let l:ep = 'sw' . l:ep
     endif
   else
     let l:ep = a:1
```

**Comment by get-me-power** [comment]
I fixed. By the way, I think that README is also should fixed. Can I open another Pull Request?

**Comment by mattn** [comment]
Please fix README in this PR. And please squash commits.

**Comment by mattn** [comment]
Okay, I squashed commits via Merge Button. Thank you.

**Pull request merged**
